onceição / AM', 'comercial': 'Largo Nascimento, 8\nVila Santa Rosa\n28899938 da Cunha da Serra / SE'}], 'telefone': [{'residencial': '+55 (081) 9560 5497', 'celular': '+55 (071) 1150-0046'}]}
{'nome': 'Pedro Vieira', '_id': 60, 'endereço': [{'residencial': 'Fazenda de Teixeira, 412\nMariquinhas\n95815007 Viana / PI', 'comercial': 'Residencial Freitas, 30\nItapoa\n36972483 Costa Grande / MS'}], 'telefone': [{'residencial': '(061) 7264-6292', 'celular':'+55 (051) 9873 5435'}]}
{'nome': 'Brenda Nascimento', '_id': 61, 'endereço': [{'residencial': 'Jardim Barbosa, 95\nCoração Eucarístico\n17886038 da Conceição de Monteiro / CE', 'comercial': 'Campo Pires, 1\nVila Antena\n76334969 Fogaça do Campo / GO'}], 'telefone': [{'residencial': '+5521 3282 9571', 'celular': '+55 (071) 8792-9435'}]}
{'nome': 'Luiz Felipe Fogaça', '_id': 62, 'endereço': [{'residencial': 'Loteamento Fogaça, 6\nSerra\n03471930 Araújo do Sul / RN', 'comercial': 'Trecho Theo Porto, 9\nSerra Do Curral\n12598-789 Rocha / MT'}], 'telefone': [{'residencial': '11 7222-2980', 'celular': '+55 (071) 3576-6152'}]}
{'nome': 'Sr. João Lucas Nunes', '_id': 63, 'endereço': [{'residencial': 'Parque Gonçalves, 36\nVila Da Ária\n83092685 Barbosa / BA', 'comercial': 'Chácara Gonçalves, 10\nBarão Homem De Melo 1ª Seção\n27211-245 Vieira / CE'}], 'telefone': [{'residencial': '+55 712522 7267', 'celular': '+55 (051) 1225-9581'}]}
{'nome': 'Isadora Barros', '_id': 64, 'endereço': [{'residencial': 'Lagoa Leandro Castro, 95\nConjunto Providencia\n52537957 Costa do Sul / AC', 'comercial': 'Sítio Alexia Nascimento, 91\nMarieta 2ª Seção\n42652-873 Almeida de Barros / MA'}], 'telefone': [{'residencial': '(071) 6304-3868', 'celular': '21 0315-4045'}]}
{'nome': 'Thiago Moura', '_id': 65, 'endereço': [{'residencial': 'Esplanada Leandro Moraes, 6\nCopacabana\n53014-886 Sales do Sul /MT', 'comercial': 'Estrada Lopes, 10\nPenha\n00895-933 Moreira da Mata / PI'}], 'telefone': [{'residencial': '51 691 3015', 'celular': '+55 71 5780-2294'}]}
{'nome': 'Bernardo Melo', '_id': 66, 'endereço': [{'residencial': 'Vereda Cavalcanti, 15\nPedreira Padro Lopes\n49369-985 Correia Verde / RN', 'comercial': 'Esplanada Novaes, 4\nSão Tomaz\n17344-883 Cunha / AL'}], 'telefone': [{'residencial': '71 0147 7158', 'celular': '+55 (031) 9862-8534'}]}
{'nome': 'Anthony Teixeira', '_id': 67, 'endereço': [{'residencial': 'Ladeira Cecília Rezende, 4\nBelvedere\n76706487 Rezende Alegre / RO', 'comercial': 'Lagoa Vieira, 30\nConjunto Providencia\n60543-804 Cardoso / RS'}], 'telefone': [{'residencial': '+55 41 8596 5283', 'celular': '(081) 8930-5961'}]}
{'nome': 'Beatriz Nascimento', '_id': 68, 'endereço': [{'residencial': 'Via de Moreira, 458\nBraúnas\n24885579 Rodrigues do Galho /GO', 'comercial': 'Favela de Nascimento, 69\nVila Independencia 3ª Seção\n52121107 da Conceição de Minas / AM'}], 'telefone': [{'residencial': '71 8305-7596', 'celular': '+55 (021) 2488 1517'}]}
{'nome': 'Olivia Silveira', '_id': 69, 'endereço': [{'residencial': 'Estação de Viana, 1\nSuzana\n03787-132 Rezende dos Dourados / AM', 'comercial': 'Praça Danilo Almeida, 4\nSantana Do Cafezal\n81529147 Almeida / MT'}], 'telefone': [{'residencial': '+55 (071) 7247 4824', 'celular': '+55 (021) 1415 8521'}]}
{'nome': 'Clara Novaes', '_id': 70, 'endereço': [{'residencial': 'Fazenda de Oliveira, 960\nVila Madre Gertrudes 1ª Seção\n23436692Ramos de Melo / TO', 'comercial': 'Conjunto de Silveira, 26\nCidade Jardim\n72862944 Peixoto / AC'}], 'telefone': [{'residencial': '(021) 1400 6363', 'celular': '(061) 4028-9814'}]}
{'nome': 'Dr. Davi Lucca Cardoso', '_id': 71, 'endereço': [{'residencial': 'Trevo Almeida, 2\nMirtes\n33476277 Fernandes de da Cruz/ AL', 'comercial': 'Viaduto de Nascimento, 410\nSport Club\n24541972 Cunha de Minas / PR'}], 'telefone': [{'residencial': '(051) 6569-0935', 'celular': '41 4429-7893'}]}
{'nome': 'João Guilherme Rezende', '_id': 72, 'endereço': [{'residencial': 'Vereda de Peixoto, 78\nUnião\n24090845 Mendes / CE', 'comercial': 'Largo de da Cunha, 578\nAlto Das Antenas\n57176-863 Peixoto / AC'}], 'telefone': [{'residencial': '+55 21 9929 0145', 'celular': '11 2314 9177'}]}
{'nome': 'Nathan Rezende', '_id': 73, 'endereço': [{'residencial': 'Viaduto de Alves, 3\nVila São Gabriel Jacui\n92139-540 Araújo das Pedras / PI', 'comercial': 'Condomínio de Fogaça, 12\nVila Engenho Nogueira\n45282159 Costa de Goiás / MT'}], 'telefone': [{'residencial': '31 1926 0593', 'celular': '81 2800 5493'}]}
{'nome': 'Vitor Santos', '_id': 74, 'endereço': [{'residencial': 'Ladeira de da Costa, 324\nJuliana\n52405088 da Mota / AL', 'comercial': 'Área Benjamin Teixeira, 29\nHorto Florestal\n43080404 Castro da Mata / ES'}], 'telefone': [{'residencial': '71 0241-6046', 'celular': '(031) 1912-0641'}]}
{'nome': 'João Lucas Teixeira', '_id': 75, 'endereço': [{'residencial': 'Alameda Ramos\nFlamengo\n27188433 da Costa do Norte / RN','comercial': 'Condomínio Ryan Jesus, 77\nNova Esperança\n37060849 Nogueira / AM'}], 'telefone': [{'residencial': '21 9530 8258', 'celular': '11 4205 6920'}]}
{'nome': 'Kaique Lopes', '_id': 76, 'endereço': [{'residencial': 'Esplanada Heloísa Farias, 41\nOuro Preto\n18555-613 da Conceição / AP', 'comercial': 'Esplanada Isadora Alves, 50\nProvidencia\n56580-373 Farias Alegre / MG'}], 'telefone': [{'residencial': '+55 51441 8511', 'celular': '+55 (011) 3504-1940'}]}
{'nome': 'Lorena Nunes', '_id': 77, 'endereço': [{'residencial': 'Praça Kaique Rezende, 67\nCanaa\n08144439 Santos / PE', 'comercial': 'Fazenda Isabelly Campos, 78\nSão Paulo\n07386-868 Santos de das Neves / MT'}], 'telefone': [{'residencial': '31 0980 1845', 'celular': '6135-7701'}]}
{'nome': 'Isabelly da Luz', '_id': 78, 'endereço': [{'residencial': 'Viaduto Brenda Barbosa, 944\nSão Benedito\n89146817 Lima dos Dourados / RS', 'comercial': 'Viela de Barros, 62\nBernadete\n83243-940 Pinto / AC'}], 'telefone': [{'residencial': '(061) 2063 8664', 'celular': '+55 (081) 2016-1735'}]}
{'nome': 'Dra. Isabella Sales', '_id': 79, 'endereço': [{'residencial': 'Avenida de Lima\nConjunto Minas Caixa\n54695704 Castro / RR', 'comercial': 'Sítio de Pereira, 1\nVila União\n76477749 Pereira de Sales / PI'}], 'telefone': [{'residencial': '71 4620-8739', 'celular': '+55 11 5081-2358'}]}
{'nome': 'Daniela Cardoso', '_id': 80, 'endereço': [{'residencial': 'Quadra de Azevedo, 14\nCoqueiros\n80008111 da Mota / AC', 'comercial': 'Trecho Renan Moraes, 2\nAlípio De Melo\n88481172 da Rocha / RN'}], 'telefone': [{'residencial': '(031) 2920-6968', 'celular': '31 2344-2109'}]}
{'nome': 'Alice Araújo', '_id': 81, 'endereço': [{'residencial': 'Rodovia Jesus, 30\nVila Maria\n05776862 Rodrigues do Campo / PB','comercial': 'Estação de Costela, 602\nVila Dos Anjos\n79834-851 da Paz do Amparo / GO'}], 'telefone': [{'residencial': '4912-3911', 'celular': '(071) 4795-9558'}]}
{'nome': 'Srta. Júlia Melo', '_id': 82, 'endereço': [{'residencial': 'Vereda Ryan Duarte, 50\nVitoria Da Conquista\n50990-226 Cunha/ AC', 'comercial': 'Quadra Martins, 53\nVila Cloris\n42047-037 da Paz / SC'}], 'telefone': [{'residencial': '+55 (021) 6027 8864','celular': '(031) 3068 2435'}]}
{'nome': 'Caio Lima', '_id': 83, 'endereço': [{'residencial': 'Trecho da Costa, 2\nLagoa\n09753-875 Moraes Verde / MA', 'comercial': 'Largo Arthur Araújo, 6\nSanta Isabel\n34445-278 da Mata da Prata / RN'}], 'telefone': [{'residencial': '+55 41 0519 8347', 'celular': '11 5287 9995'}]}
{'nome': 'Daniel da Luz', '_id': 84, 'endereço': [{'residencial': 'Morro Porto, 68\nVila Betânia\n66492-567 Ramos de Pereira / PR','comercial': 'Travessa Emanuel Monteiro, 386\nVila Copacabana\n55363814 Araújo Paulista / CE'}], 'telefone': [{'residencial': '+55 21 3129 3349', 'celular': '(061) 2743 2873'}]}
{'nome': 'Ana Luiza Barbosa', '_id': 85, 'endereço': [{'residencial': 'Quadra Pedro Lucas Fernandes\nFazendinha\n71719-102 da Cunhade Peixoto / BA', 'comercial': 'Ladeira Alves, 51\nMonsenhor Messias\n31483847 Araújo de Oliveira / PR'}], 'telefone': [{'residencial': '51 478 0337', 'celular': '11 8110-4688'}]}
{'nome': 'Ana Ferreira', '_id': 86, 'endereço': [{'residencial': 'Trecho de Fogaça, 63\nVila Boa Vista\n75139673 Costela / BA', 'comercial': 'Largo de Freitas, 707\nCoração De Jesus\n45770325 Cardoso / RO'}], 'telefone': [{'residencial': '21 6866 3834', 'celular': '(021) 4043-3792'}]}
{'nome': 'Dr. Leonardo da Cruz', '_id': 87, 'endereço': [{'residencial': 'Campo de Duarte\nVila Paris\n81292-045 Novaes da Serra / AM', 'comercial': 'Lago Agatha da Cruz, 5\nVila Da Amizade\n58623960 da Costa de Gonçalves / MA'}], 'telefone': [{'residencial': '+55 (011) 3731-4796', 'celular': '+55 11 6995 8636'}]}
{'nome': 'Murilo Cavalcanti', '_id': 88, 'endereço': [{'residencial': 'Núcleo Oliveira, 646\nVila Oeste\n80974-009 Castro de Campos/ PE', 'comercial': 'Distrito Carolina Nascimento, 8\nVila Calafate\n75852-673 Araújo de Goiás / RR'}], 'telefone': [{'residencial': '(061) 8707 1496', 'celular': '11 1005 5930'}]}
{'nome': 'Sr. Lucas Gabriel Costa', '_id': 89, 'endereço': [{'residencial': 'Chácara Nascimento\nSanta Amelia\n09499698 da Paz / DF', 'comercial': 'Residencial Mariana Gonçalves, 30\nIpiranga\n65297260 da Cruz da Serra / RO'}], 'telefone': [{'residencial': '(051)0640-1848', 'celular': '+55 41 8934-8908'}]}
{'nome': 'Nicole Fernandes', '_id': 90, 'endereço': [{'residencial': 'Rua Sales, 2\nErnesto Nascimento\n70041-073 da Conceição das Pedras / MS', 'comercial': 'Favela de Castro, 57\nVila Santa Monica 2ª Seção\n55405372 Nascimento de Lopes / DF'}], 'telefone': [{'residencial': '1041 1372', 'celular': '+55 31 2987 5930'}]}
{'nome': 'Sr. Levi Nascimento', '_id': 91, 'endereço': [{'residencial': 'Pátio Pires, 57\nPiratininga\n32415-212 Nunes / MS', 'comercial': 'Rua Cardoso\nVila Paquetá\n56515193 Barros / AP'}], 'telefone': [{'residencial': '+55 21 6561-3837', 'celular': '+55 31 2971-4311'}]}
{'nome': 'Benjamin Rodrigues', '_id': 92, 'endereço': [{'residencial': 'Quadra de Fernandes\nCenaculo\n34811-475 Castro das Flores / DF', 'comercial': 'Lago Helena Nogueira, 451\nRibeiro De Abreu\n68958239 Lima de Campos / RO'}], 'telefone': [{'residencial': '(051) 0413-3296', 'celular': '+55 (081) 6767 6116'}]}
{'nome': 'Carlos Eduardo Fernandes', '_id': 93, 'endereço': [{'residencial': 'Lago Mendes, 9\nTeixeira Dias\n96481-804 Costa / PI','comercial': 'Lagoa de Cardoso, 4\nJoão Alfredo\n83239-160 Pires / MT'}], 'telefone': [{'residencial': '11 4219-4698', 'celular': '+55 (081) 4684 4747'}]}
^CTraceback (most recent call last):
  File "Faker.py", line 30, in <module>
    sleep(1)
KeyboardInterrupt
developer@developer:~/520/Aula-4$ pip3 install sqlalchemy
Collecting sqlalchemy
  Downloading https://files.pythonhosted.org/packages/25/c9/b0552098cee325425a61efdf380c51b5c721e459081c85bbb860f501c091/SQLAlchemy-1.2.12.tar.gz (5.6MB)
    100% |████████████████████████████████| 5.6MB 49kB/s
Building wheels for collected packages: sqlalchemy
  Running setup.py bdist_wheel for sqlalchemy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-m925dp2c/sqlalchemy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpup195_3gpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for sqlalchemy
  Running setup.py clean for sqlalchemy
Failed to build sqlalchemy
Installing collected packages: sqlalchemy
  Running setup.py install for sqlalchemy ... done
Successfully installed sqlalchemy-1.2.12
developer@developer:~/520/Aula-4$ cd SQLAlchemy/
developer@developer:~/520/Aula-4/SQLAlchemy$ ls
core_insert.py  core.py
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
Traceback (most recent call last):
  File "core.py", line 3, in <module>
    from SQLAlchemy import (create_engine, MetaData, Table, Column, Integer, String, DateTime)
ImportError: No module named 'SQLAlchemy'
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
Traceback (most recent call last):
  File "core.py", line 3, in <module>
    from SQLAlchemy import (create_engine, MetaData, Table, Column, Integer, String, DateTime)
ImportError: No module named 'SQLAlchemy'
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
Traceback (most recent call last):
  File "core.py", line 7, in <module>
    engine = create_engine('sqllite:///teste.db', echo=True)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 57, in create
    entrypoint = u._get_entrypoint()
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 221, in load
    (self.group, name))
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
Traceback (most recent call last):
  File "core.py", line 7, in <module>
    engine = create_engine('sqllite:///teste.db', echo=True)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 57, in create
    entrypoint = u._get_entrypoint()
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 221, in load
    (self.group, name))
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:sqllite
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
Traceback (most recent call last):
  File "core.py", line 17, in <module>
    Column('atualizado_em', DateTime, default=datetime.now, onipdate=datetime.now)
  File "/home/developer/.local/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 1289, in __init__
    "Unknown arguments passed to Column: " + repr(list(kwargs)))
sqlalchemy.exc.ArgumentError: Unknown arguments passed to Column: ['onipdate']
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core.py
2018-09-22 14:08:09,031 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:08:09,032 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:09,034 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:08:09,034 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:09,037 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:08:09,037 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:09,045 INFO sqlalchemy.engine.base.Engine
CREATE TABLE usuarios (
        id INTEGER NOT NULL,
        nome VARCHAR(40),
        idade INTEGER NOT NULL,
        senha VARCHAR,
        criado_em DATETIME,
        atualizado_em DATETIME,
        PRIMARY KEY (id)
)


2018-09-22 14:08:09,046 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:09,073 INFO sqlalchemy.engine.base.Engine COMMIT
2018-09-22 14:08:09,074 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_usuarios_nome ON usuarios (nome)
2018-09-22 14:08:09,074 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:09,090 INFO sqlalchemy.engine.base.Engine COMMIT
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_insert.py
2018-09-22 14:08:38,302 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:08:38,303 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:38,304 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:08:38,304 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:38,308 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:08:38,311 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:08:38,337 INFO sqlalchemy.engine.base.Engine INSERT INTO usuarios (nome, idade, senha, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?)
2018-09-22 14:08:38,338 INFO sqlalchemy.engine.base.Engine ('daniel', 24, 'teste123', '2018-09-22 14:08:38.337058', '2018-09-22 14:08:38.337485')
2018-09-22 14:08:38,357 INFO sqlalchemy.engine.base.Engine COMMIT
2018-09-22 14:08:38,373 INFO sqlalchemy.engine.base.Engine INSERT INTO usuarios (nome, idade, senha, criado_em, atualizado_em) VALUES (?, ?, ?, ?, ?)
2018-09-22 14:08:38,374 INFO sqlalchemy.engine.base.Engine (('marcio', 21, 'semsenha', '2018-09-22 14:08:38.373668', '2018-09-22 14:08:38.373700'), ('gustavo', 18, 'abacaxi123', '2018-09-22 14:08:38.373714', '2018-09-22 14:08:38.373727'), ('guilherme', 22, 'goiaba123', '2018-09-22 14:08:38.373741', '2018-09-22 14:08:38.373754'))
2018-09-22 14:08:38,374 INFO sqlalchemy.engine.base.Engine COMMIT
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_select.py
2018-09-22 14:12:52,724 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:12:52,726 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:12:52,727 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:12:52,728 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:12:52,729 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:12:52,729 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:12:52,740 INFO sqlalchemy.engine.base.Engine SELECT usuarios.id, usuarios.nome, usuarios.idade, usuarios.senha, usuarios.criado_em, usuarios.atualizado_em
FROM usuarios
WHERE usuarios.nome = ?
2018-09-22 14:12:52,740 INFO sqlalchemy.engine.base.Engine ('daniel',)
[(1, 'daniel', 24, 'teste123', datetime.datetime(2018, 9, 22, 14, 8, 38, 337058), datetime.datetime(2018, 9, 22, 14, 8, 38, 337485))]
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_update.py.py
python3: can't open file 'core_update.py.py': [Errno 2] No such file or directory
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_update.py
2018-09-22 14:17:21,864 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:17:21,866 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:17:21,868 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:17:21,868 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:17:21,870 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:17:21,870 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:17:21,879 INFO sqlalchemy.engine.base.Engine UPDATE usuarios SET nome=?, atualizado_em=? WHERE usuarios.nome = ?
2018-09-22 14:17:21,880 INFO sqlalchemy.engine.base.Engine ('daniel prata', '2018-09-22 14:17:21.879341', 'daniel')
2018-09-22 14:17:21,885 INFO sqlalchemy.engine.base.Engine COMMIT
1
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_update.py
2018-09-22 14:18:08,700 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:18:08,701 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:18:08,708 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:18:08,708 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:18:08,711 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:18:08,711 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:18:08,721 INFO sqlalchemy.engine.base.Engine UPDATE usuarios SET nome=?, atualizado_em=? WHERE usuarios.nome = ?
2018-09-22 14:18:08,721 INFO sqlalchemy.engine.base.Engine ('daniel prata', '2018-09-22 14:18:08.721054', 'daniel')
2018-09-22 14:18:08,728 INFO sqlalchemy.engine.base.Engine COMMIT
linhas afetas: 0
developer@developer:~/520/Aula-4/SQLAlchemy$ python3 core_delete.py
2018-09-22 14:22:24,487 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:22:24,489 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:22:24,490 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-09-22 14:22:24,491 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:22:24,492 INFO sqlalchemy.engine.base.Engine PRAGMA table_info("usuarios")
2018-09-22 14:22:24,492 INFO sqlalchemy.engine.base.Engine ()
2018-09-22 14:22:24,504 INFO sqlalchemy.engine.base.Engine DELETE FROM usuarios WHERE usuarios.nome = ?
2018-09-22 14:22:24,504 INFO sqlalchemy.engine.base.Engine ('daniel prata',)
2018-09-22 14:22:24,510 INFO sqlalchemy.engine.base.Engine COMMIT
linhas afetas: 1
developer@developer:~/520/Aula-4/SQLAlchemy$ cd ..
developer@developer:~/520/Aula-4$
developer@developer:~/520/Aula-4$ cd ..
developer@developer:~/520$ ls
Aula-1  Aula-2  Aula-3  Aula-4  doc.txt  Flask  git_command.txt  venv
developer@developer:~/520$ cd Flask/
developer@developer:~/520/Flask$ ls
app2.py  app.py
developer@developer:~/520/Flask$ python3 app2.py app
Traceback (most recent call last):
  File "app2.py", line 1, in <module>
    from flask import Flask, jsonify
ImportError: No module named 'flask'
developer@developer:~/520/Flask$ python3 app2.py
Traceback (most recent call last):
  File "app2.py", line 1, in <module>
    from flask import Flask, jsonify
ImportError: No module named 'flask'
developer@developer:~/520/Flask$ python3 app2.py
Traceback (most recent call last):
  File "app2.py", line 1, in <module>
    from flask import Flask, jsonify
ImportError: No module named 'flask'
developer@developer:~/520/Flask$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, jsonify
ImportError: No module named 'flask'
developer@developer:~/520/Flask$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, jsonify
ImportError: No module named 'flask'
developer@developer:~/520/Flask$ pip3 install Flask
Collecting Flask
  Downloading https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.0MB/s
Collecting Werkzeug>=0.14 (from Flask)
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 830kB/s
Collecting itsdangerous>=0.24 (from Flask)
  Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 1.6MB/s
Collecting Jinja2>=2.10 (from Flask)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 923kB/s
Collecting click>=5.1 (from Flask)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.0MB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask)
  Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Building wheels for collected packages: itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for itsdangerous ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yf5c04ah/itsdangerous/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp3d_6zw9qpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for itsdangerous
  Running setup.py clean for itsdangerous
  Running setup.py bdist_wheel for MarkupSafe ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yf5c04ah/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprryncvdtpip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
Failed to build itsdangerous MarkupSafe
Installing collected packages: Werkzeug, itsdangerous, MarkupSafe, Jinja2, click, Flask
  Running setup.py install for itsdangerous ... done
  Running setup.py install for MarkupSafe ... done
Successfully installed Flask-1.0.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 itsdangerous-0.24
developer@developer:~/520/Flask$ python3 app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 14:39:49] "GET / HTTP/1.1" 200 -
^Cdeveloper@developer:~/520/Flask$ python3 app2.py
 * Serving Flask app "app2" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 14:40:11] "GET / HTTP/1.1" 404 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "app2.py", line 4, in <module>
    import psycopg2
ImportError: No module named 'psycopg2'
developer@developer:~/520/Flask$ python3 app2.py
Traceback (most recent call last):
  File "app2.py", line 4, in <module>
    import psycopg2
ImportError: No module named 'psycopg2'
developer@developer:~/520/Flask$ pip3 install psyycopg2
Collecting psyycopg2
  Could not find a version that satisfies the requirement psyycopg2 (from versions: )
No matching distribution found for psyycopg2
developer@developer:~/520/Flask$ pip3 install psycopg2
Collecting psycopg2
  Downloading https://files.pythonhosted.org/packages/53/fc/dfc645d6b89cbc288b0d7b8bc9e83b8052ef263781562a89ec748e8ae008/psycopg2-2.7.5-cp35-cp35m-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 168kB/s
Installing collected packages: psycopg2
Successfully installed psycopg2-2.7.5
developer@developer:~/520/Flask$ python3 app2.py
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "app2.py", line 13, in <module>
    'host=127.0.0.1 dbname=fundamentals user=admin password=4linux')
  File "/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  banco de dados "fundamentals" não existe

developer@developer:~/520/Flask$ python3 app2.py
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Serving Flask app "app2" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 15:48:20] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 15:48:28] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 34, in index
    return jsonify(lista)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:48:28] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:48:28] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:48:28] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:48:29] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:48:29] "GET /mongo?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:48:29] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /postgresql HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 19, in postgres
    cur.execute("select * from usuarios;")
psycopg2.ProgrammingError: ERRO:  relação "usuarios" não existe
LINE 1: select * from usuarios;
                      ^
127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /postgresql?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /postgresql?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /postgresql?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:00] "GET /postgresql?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /postgresql?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:01] "GET /postgresql?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 34, in index
    return jsonify(lista)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:49:14] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 15:50:24] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 35, in index
    return jsonify(lista)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:50:24] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:50:24] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:50:24] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:50:24] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:50:25] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:10] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:26] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 35, in index
    return jsonify(lista)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:52:37] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 36, in index
    return jsonify(dumps(lista))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:54:50] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:55:57] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 36, in index
    return jsonify(dumps(lista))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:55:57] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:55:57] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:55:57] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:55:57] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:55:58] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:56:00] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 36, in index
    return jsonify(dumps(lista))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 15:56:01] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:56:01] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:56:01] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:56:01] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 15:56:01] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:01:48] "GET /postgres HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 21, in postgres
    cur.execute("select * from usuarios;")
psycopg2.ProgrammingError: ERRO:  relação "usuarios" não existe
LINE 1: select * from usuarios;
                      ^
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:01:51] "GET /postgresql?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "app2.py", line 38, in <module>
    @app.route('/mongo2')
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: index
developer@developer:~/520/Flask$ python3 app2.py
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "app2.py", line 38, in <module>
    @app.route('/mongo2')
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: index
developer@developer:~/520/Flask$ python3 app2.py
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Serving Flask app "app2" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 16:06:31] "GET /postgresql HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
  File "app2.py", line 32
    def mongo()):
               ^
SyntaxError: invalid syntax
developer@developer:~/520/Flask$ python3 app2.py
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Serving Flask app "app2" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 16:14:26] "GET /mongo HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/developer/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/developer/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/developer/520/Flask/app2.py", line 36, in mongo
    return jsonify(dumps(lista))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ObjectId('5ba657dbe3d0b54435705f71') is not JSON serializable
127.0.0.1 - - [22/Sep/2018 16:14:26] "GET /mongo?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:14:26] "GET /mongo?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:14:26] "GET /mongo?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:14:26] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:14:27] "GET /mongo?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:14:30] "GET /mongo2 HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 16:16:40] "GET /mongo2 HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:16:45] "GET /teste HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 16:17:33] "GET /teste HTTP/1.1" 200 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Debugger is active!
 * Debugger PIN: 172-246-297
127.0.0.1 - - [22/Sep/2018 16:41:00] "GET /teste/Larissa%20Melo HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:41:56] "GET /teste/Larissa%20Melo HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:41:59] "GET /teste/Larissa%20Melo HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:42:03] "GET /teste/ HTTP/1.1" 404 -
127.0.0.1 - - [22/Sep/2018 16:42:13] "GET /mongo2 HTTP/1.1" 200 -
127.0.0.1 - - [22/Sep/2018 16:42:34] "GET /teste/Bruna%20Martins HTTP/1.1" 404 -
 * Detected change in '/home/developer/520/Flask/app2.py', reloading
 * Restarting with stat
/home/developer/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http:developer@developer:~/520/Flask$





Configurando python2.7 (2.7.13-2+deb9u2) ...
Configurando libgd3:amd64 (2.2.4-2+deb9u2) ...
Configurando libiptc0:amd64 (1.6.0+snapshot20161117-6) ...
Configurando gir1.2-gdkpixbuf-2.0:amd64 (2.36.5-2+deb9u2) ...
Configurando libnl-genl-3-200:amd64 (3.2.27-2) ...
Configurando libnss3:amd64 (2:3.26.2-1.1+deb9u1) ...
Configurando libxfont2:amd64 (1:2.0.1-3+deb9u1) ...
Configurando ssl-cert (1.0.39) ...
Configurando initramfs-tools (0.130) ...
update-initramfs: deferring update (trigger activated)
Configurando ruby2.3 (2.3.3-1+deb9u3) ...
Configurando mongodb-server (1:3.2.11-2+deb9u1) ...
Configurando libxatracker2:amd64 (13.0.6-1+b2) ...
Configurando file (1:5.30-1+deb9u2) ...
Configurando libmtp-runtime (1.1.13-1) ...
Configurando libsasl2-dev (2.1.27~101-g0780600+dfsg-3) ...
Configurando libxkbcommon-x11-0:amd64 (0.7.1-2~deb9u1) ...
Configurando python-numpy (1:1.12.1-3) ...
Configurando libgnome-keyring0:amd64 (3.12.0-1+b2) ...
Configurando gir1.2-javascriptcoregtk-4.0:amd64 (2.18.6-1~deb9u1) ...
Configurando gcc-6 (6.3.0-18+deb9u1) ...
Configurando isc-dhcp-client (4.3.5-3+deb9u1) ...
Configurando libpangoft2-1.0-0:amd64 (1.40.5-1) ...
Configurando libgpgme11:amd64 (1.8.0-3+b2) ...
Configurando libgoa-1.0-0b:amd64 (3.22.5-1) ...
Configurando g++-6 (6.3.0-18+deb9u1) ...
Configurando p7zip-full (16.02+dfsg-3+deb9u1) ...
Configurando gcj-6-jre-lib (6.3.0-18+deb9u1) ...
Configurando deluge-gtk (1.3.13+git20161130.48cedf63-3) ...
Configurando libisccc140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u4) ...
Configurando python3-reportbug (7.1.7+deb9u2) ...
Configurando gtk-update-icon-cache (3.22.11-1) ...
Configurando dpkg-dev (1.18.25) ...
Configurando libtracker-sparql-1.0-0:amd64 (1.10.5-1) ...
Configurando libxdmcp-dev:amd64 (1:1.1.2-3) ...
Configurando libpolkit-backend-1-0:amd64 (0.105-18) ...
Configurando linux-kbuild-4.9 (4.9.110-3+deb9u4) ...
Configurando libgl1-mesa-glx:amd64 (13.0.6-1+b2) ...
Configurando iptables (1.6.0+snapshot20161117-6) ...
Configurando libldap-2.4-2:amd64 (2.4.44+dfsg-5+deb9u2) ...
Configurando lm-sensors (1:3.4.0-4) ...
Configurando gvfs-libs:amd64 (1.30.4-1) ...
Configurando libespeak-ng1:amd64 (1.49.0+dfsg-11) ...
Configurando libgmime-2.6-0:amd64 (2.6.22+dfsg2-1) ...
Configurando php7.0-json (7.0.30-0+deb9u1) ...
Configurando mesa-va-drivers:amd64 (13.0.6-1+b2) ...
Configurando rtkit (0.11-4+b1) ...
Created symlink /etc/systemd/system/graphical.target.wants/rtkit-daemon.service → /lib/systemd/system/rtkit-daemon.service.
Configurando bluez-obexd (5.43-2+deb9u1) ...
Configurando libwayland-egl1-mesa:amd64 (13.0.6-1+b2) ...
Configurando ntfs-3g (1:2016.2.22AR.1+dfsg-1) ...
Configurando libpython2.7:amd64 (2.7.13-2+deb9u2) ...
Configurando libatk-bridge2.0-0:amd64 (2.22.0-2) ...
Configurando wget (1.18-5+deb9u2) ...
Configurando gir1.2-gnomekeyring-1.0 (3.12.0-1+b2) ...
Configurando lintian (2.5.50.4) ...
Configurando libice6:amd64 (2:1.0.9-2) ...
Configurando deluge (1.3.13+git20161130.48cedf63-3) ...
Configurando x11-xserver-utils (7.7+7+b1) ...
Configurando dnsmasq-base (2.76-5+deb9u1) ...
Configurando libexpat1-dev:amd64 (2.2.0-2+deb9u1) ...
A processar 'triggers' para man-db (2.7.6.1-2) ...
Configurando libkrb5-3:amd64 (1.15-1+deb9u1) ...
Configurando libpython2.7-dev:amd64 (2.7.13-2+deb9u2) ...
Configurando dbus (1.10.26-0+deb9u1) ...
A reboot is required to replace the running dbus-daemon.
Please reboot the system when convenient.
Configurando libvorbisenc2:amd64 (1.3.5-4+deb9u2) ...
Configurando python-dbus (1.2.4-1+b1) ...
Configurando libopencv-video2.4v5:amd64 (2.4.9.1+dfsg1-2) ...
Configurando mariadb-server-10.1 (10.1.26-0+deb9u1) ...
Instalando nova versão do arquivo de configuração /etc/init.d/mysql ...
Instalando nova versão do arquivo de configuração /etc/logrotate.d/mysql-server ...
Configurando mariadb-plugin-spider (10.1.26-0+deb9u1) ...
@have_spider_plugin := 1
1
@have_spider_i_s_alloc_mem_plugin := 1
1
@have_spider_direct_sql_udf := 1
1
@have_spider_bg_direct_sql_udf := 1
1
@have_spider_ping_table_udf := 1
1
@have_spider_copy_tables_udf := 1
1
@have_spider_flush_table_mon_cache_udf := 1
1
Configurando bluez (5.43-2+deb9u1) ...
Configurando gir1.2-gstreamer-1.0 (1.10.4-1) ...
Configurando python2.7-dev (2.7.13-2+deb9u2) ...
Configurando sane-utils (1.0.25-4.1) ...
Configurando mate-icon-theme (1.16.2-1) ...
Configurando discover (2.1.2-7.1+deb9u1) ...
Configurando mate-themes (3.22.11-1+deb9u1) ...
Configurando adwaita-icon-theme (3.22.0-1+deb9u1) ...
Configurando libatk-adaptor:amd64 (2.22.0-2) ...
Configurando vim-tiny (2:8.0.0197-4+deb9u1) ...
Configurando libgstreamer-plugins-base1.0-0:amd64 (1.10.4-1) ...
Configurando gir1.2-atspi-2.0:amd64 (2.22.0-6+deb9u1) ...
Configurando gstreamer1.0-plugins-base:amd64 (1.10.4-1) ...
Configurando libgupnp-dlna-2.0-3 (0.10.5-3+b1) ...
Configurando libnotify4:amd64 (0.7.7-2) ...
Configurando libsm6:amd64 (2:1.2.2-1+b3) ...
Configurando gir1.2-notify-0.7:amd64 (0.7.7-2) ...
Configurando libnm-util2:amd64 (1.6.2-3) ...
Configurando xserver-common (2:1.19.2-1+deb9u2) ...
Configurando ca-certificates-java (20170531+nmu1) ...
Configurando mariadb-plugin-cracklib-password-check (10.1.26-0+deb9u1) ...
Configurando libpam-systemd:amd64 (232-25+deb9u4) ...
Configurando x11-session-utils (7.7+2+b1) ...
Configurando libnm-glib4:amd64 (1.6.2-3) ...
Configurando powertop (2.8-1+b1) ...
Configurando mariadb-plugin-mroonga (10.1.26-0+deb9u1) ...
ERROR 1968 (HY000) at line 3: Plugin 'Mroonga' already installed
Configurando cracklib-runtime (2.9.2-5) ...
Configurando policykit-1 (0.105-18) ...
Removed /run/systemd/system/polkit.service.
Configurando xarchiver (1:0.5.4-7) ...
Configurando libnm0:amd64 (1.6.2-3) ...
Configurando libpoppler64:amd64 (0.48.0-2+deb9u2) ...
Configurando libavcodec57:amd64 (7:3.2.12-1~deb9u1) ...
Configurando libpangoxft-1.0-0:amd64 (1.40.5-1) ...
Configurando apache2-bin (2.4.25-3+deb9u5) ...
Configurando dbus-x11 (1.10.26-0+deb9u1) ...
Configurando wpasupplicant (2:2.4-1+deb9u1) ...
Configurando gir1.2-gst-plugins-base-1.0 (1.10.4-1) ...
Configurando x11-utils (7.7+3+b1) ...
Configurando libpangocairo-1.0-0:amd64 (1.40.5-1) ...
Configurando gcc (4:6.3.0-4) ...
Configurando php7.0-cli (7.0.30-0+deb9u1) ...
Replacing config file /etc/php/7.0/cli/php.ini with new version
Configurando xserver-xorg-core (2:1.19.2-1+deb9u2) ...
Configurando linux-compiler-gcc-6-x86 (4.9.110-3+deb9u4) ...
Configurando dbus-user-session (1.10.26-0+deb9u1) ...
Configurando gcj-6-jre-headless (6.3.0-18+deb9u1) ...
Configurando gir1.2-pango-1.0:amd64 (1.40.5-1) ...
Configurando reportbug (7.1.7+deb9u2) ...
Configurando libgssapi-krb5-2:amd64 (1.15-1+deb9u1) ...
Configurando libgstreamer-plugins-bad1.0-0:amd64 (1.10.4-1) ...
Configurando libgcj17-awt:amd64 (6.3.0-18+deb9u1) ...
Configurando libsndfile1:amd64 (1.0.27-3) ...
Configurando gcj-jre-headless (4:6.3.0-4) ...
Configurando mariadb-plugin-gssapi-server (10.1.26-0+deb9u1) ...
Configurando pcmanfm (1.2.5-3) ...
Configurando bluetooth (5.43-2+deb9u1) ...
Configurando mariadb-test (10.1.26-0+deb9u1) ...
Configurando libice-dev:amd64 (2:1.0.9-2) ...
Configurando mariadb-plugin-connect (10.1.26-0+deb9u1) ...
Configurando gcj-6-jre (6.3.0-18+deb9u1) ...
Configurando lxterminal (0.3.0-2) ...
Configurando mariadb-plugin-oqgraph (10.1.26-0+deb9u1) ...
Configurando g++ (4:6.3.0-4) ...
Configurando gstreamer1.0-plugins-ugly:amd64 (1.10.4-1) ...
Configurando x11-apps (7.7+6+b1) ...
Configurando mariadb-server (10.1.26-0+deb9u1) ...
Configurando gstreamer1.0-x:amd64 (1.10.4-1) ...
Configurando libatk-wrapper-java (0.33.3-13+deb9u1) ...
Configurando openssh-client (1:7.4p1-10+deb9u4) ...
Configurando libavformat57:amd64 (7:3.2.12-1~deb9u1) ...
Configurando gcj-jre (4:6.3.0-4) ...
Configurando libcups2:amd64 (2.2.1-8+deb9u2) ...
Configurando libgksu2-0 (2.0.13~pre1-9+b1) ...
Configurando libnm-glib-vpn1:amd64 (1.6.2-3) ...
Configurando libsm-dev:amd64 (2:1.2.2-1+b3) ...
Configurando libpoppler-glib8:amd64 (0.48.0-2+deb9u2) ...
Configurando libdns162:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u4) ...
Configurando gvfs-daemons (1.30.4-1) ...
Configurando samba-libs:amd64 (2:4.5.12+dfsg-2+deb9u3) ...
A processar 'triggers' para gconf2 (3.2.6-4+b1) ...
Configurando poppler-utils (0.48.0-2+deb9u2) ...
Configurando apache2 (2.4.25-3+deb9u5) ...
Instalando nova versão do arquivo de configuração /etc/init.d/apache-htcacheclean ...
Configurando xserver-xorg-video-nouveau (1:1.0.13-3) ...
Configurando libapache2-mod-php7.0 (7.0.30-0+deb9u1) ...
Replacing config file /etc/php/7.0/apache2/php.ini with new version
libapache2-mod-php7.0: not switching MPM - already enabled
Configurando libcurl3-gnutls:amd64 (7.52.1-5+deb9u7) ...
Configurando gksu (2.0.2-9+b1) ...
Configurando system-config-printer-udev (1.5.7-3+b1) ...
Configurando libavfilter6:amd64 (7:3.2.12-1~deb9u1) ...
Configurando libisccfg140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u4) ...
Configurando libsoup2.4-1:amd64 (2.56.0-2+deb9u2) ...
Configurando xserver-xorg-video-all (1:7.7+19) ...
Configurando libsoup-gnome2.4-1:amd64 (2.56.0-2+deb9u2) ...
Configurando mariadb-plugin-gssapi-client (10.1.26-0+deb9u1) ...
Configurando libgtk-3-0:amd64 (3.22.11-1) ...
Configurando xdg-user-dirs-gtk (0.10-1+b1) ...
Configurando libpulse0:amd64 (10.0-1+deb9u1) ...
Configurando gir1.2-soup-2.4:amd64 (2.56.0-2+deb9u2) ...
Configurando mousetweaks (3.12.0-1+b1) ...
Configurando libsmbclient:amd64 (2:4.5.12+dfsg-2+deb9u3) ...
Configurando libopencv-highgui2.4-deb0:amd64 (2.4.9.1+dfsg1-2) ...
Configurando gvfs:amd64 (1.30.4-1) ...
Configurando file-roller (3.22.3-1) ...
Configurando gnome-screenshot (3.22.0-1+b1) ...
Configurando libcupsimage2:amd64 (2.2.1-8+deb9u2) ...
Configurando network-manager (1.6.2-3) ...
Configurando libgtk-3-bin (3.22.11-1) ...
Configurando cups-pk-helper (0.2.6-1+b1) ...
Configurando libatk-wrapper-java-jni:amd64 (0.33.3-13+deb9u1) ...
Configurando grilo-plugins-0.3:amd64 (0.3.3-1+deb9u1) ...
Configurando openssh-sftp-server (1:7.4p1-10+deb9u4) ...
Configurando libgcr-ui-3-1:amd64 (3.20.0-5.1) ...
Configurando libgit2-24:amd64 (0.25.1+really0.24.6-1) ...
Configurando libnautilus-extension1a:amd64 (3.22.3-1+deb9u1) ...
Configurando code (1.27.2-1536736588) ...
Configurando libgail-3-0:amd64 (3.22.11-1) ...
Configurando speech-dispatcher-audio-plugins:amd64 (0.8.6-4+deb9u1) ...
Configurando gstreamer1.0-plugins-good:amd64 (1.10.4-1) ...
Configurando libbind9-140:amd64 (1:9.10.3.dfsg.P4-12.3+deb9u4) ...
Configurando libopencv-objdetect2.4v5:amd64 (2.4.9.1+dfsg1-2) ...
Configurando gnome-font-viewer (3.22.0-1+b1) ...
Configurando libgs9:amd64 (9.20~dfsg-3.2+deb9u5) ...
Configurando git (1:2.11.0-3+deb9u3) ...
Configurando nautilus (3.22.3-1+deb9u1) ...
Configurando gcr (3.20.0-5.1) ...
Configurando librygel-renderer-2.6-2 (0.32.1-3) ...
Configurando libclutter-1.0-0:amd64 (1.26.0+dfsg-3) ...
Configurando gnome-system-tools (3.0.0-6) ...
Configurando bind9-host (1:9.10.3.dfsg.P4-12.3+deb9u4) ...
Configurando librygel-server-2.6-2 (0.32.1-3) ...
Configurando gvfs-backends (1.30.4-1) ...
Configurando speech-dispatcher (0.8.6-4+deb9u1) ...
usermod : nenhuma mudança
Configurando gstreamer1.0-libav:amd64 (1.10.4-1) ...
Configurando libavdevice57:amd64 (7:3.2.12-1~deb9u1) ...
Configurando apt-transport-https (1.4.8) ...
Configurando libpulse-mainloop-glib0:amd64 (10.0-1+deb9u1) ...
Configurando libgjs0e (1.46.0-1+b2) ...
Configurando gir1.2-gtk-3.0:amd64 (3.22.11-1) ...
Configurando libpulsedsp:amd64 (10.0-1+deb9u1) ...
Configurando gstreamer1.0-pulseaudio:amd64 (1.10.4-1) ...
Configurando php7.0 (7.0.30-0+deb9u1) ...
Configurando pulseaudio-utils (10.0-1+deb9u1) ...
Configurando libwebkit2gtk-4.0-37:amd64 (2.18.6-1~deb9u1) ...
Configurando libwebkit2gtk-4.0-37-gtk2:amd64 (2.18.6-1~deb9u1) ...
Configurando gvfs-fuse (1.30.4-1) ...
Configurando libgnome-bluetooth13:amd64 (3.20.1-1) ...
Configurando libevdocument3-4:amd64 (3.22.1-3+deb9u1) ...
Configurando libcscreensaver0:amd64 (3.2.13-4) ...
Configurando ghostscript (9.20~dfsg-3.2+deb9u5) ...
Configurando synaptic (0.84.2) ...
Configurando libopencv-features2d2.4v5:amd64 (2.4.9.1+dfsg1-2) ...
Configurando gnome-terminal (3.22.2-1) ...
Configurando eog (3.20.5-1+b1) ...
Configurando gir1.2-clutter-1.0:amd64 (1.26.0+dfsg-3) ...
Configurando openssh-server (1:7.4p1-10+deb9u4) ...
Instalando nova versão do arquivo de configuração /etc/init.d/ssh ...
Instalando nova versão do arquivo de configuração /etc/init/ssh.conf ...
Instalando nova versão do arquivo de configuração /etc/network/if-up.d/openssh-server ...
Replacing config file /etc/ssh/sshd_config with new version
Configurando libevview3-3:amd64 (3.22.1-3+deb9u1) ...
Configurando gnome-bluetooth (3.20.1-1) ...
Configurando rygel (0.32.1-3) ...
Configurando libclutter-gtk-1.0-0:amd64 (1.8.2-2) ...
Configurando ffmpeg (7:3.2.12-1~deb9u1) ...
Configurando libclutter-gst-3.0-0:amd64 (3.0.24-1) ...
Configurando gir1.2-evince-3.0:amd64 (3.22.1-3+deb9u1) ...
Configurando speech-dispatcher-espeak-ng (0.8.6-4+deb9u1) ...
Configurando cinnamon-screensaver (3.2.13-4) ...
Configurando mpv (0.23.0-2+deb9u2) ...
Configurando gnome-orca (3.22.2-3) ...
Configurando evince (3.22.1-3+deb9u1) ...
Configurando pulseaudio (10.0-1+deb9u1) ...
Configurando gstreamer1.0-clutter-3.0 (3.0.24-1) ...
Configurando libgoa-backend-1.0-1:amd64 (3.22.5-1) ...
Configurando gir1.2-gtkclutter-1.0:amd64 (1.8.2-2) ...
Configurando zenity (3.22.0-1+b1) ...
Configurando gnome-settings-daemon (3.22.2-2+deb9u2) ...
Configurando pavucontrol (3.0-3.1) ...
Configurando libopencv-calib3d2.4v5:amd64 (2.4.9.1+dfsg1-2) ...
Configurando gnome-online-accounts (3.22.5-1) ...
Configurando gir1.2-webkit2-4.0:amd64 (2.18.6-1~deb9u1) ...
Configurando gnome-control-center (1:3.22.2-3) ...
Configurando cinnamon-screensaver-x-plugin (3.2.13-4) ...
Configurando gstreamer1.0-plugins-bad:amd64 (1.10.4-1) ...
Configurando smplayer (16.11.0~ds0-1+deb9u1) ...
Configurando gnome-user-share (3.18.3-1+b1) ...
Configurando pulseaudio-module-bluetooth (10.0-1+deb9u1) ...
Configurando gir1.2-clutter-gst-3.0:amd64 (3.0.24-1) ...
Configurando smplayer-l10n (16.11.0~ds0-1+deb9u1) ...
A processar 'triggers' para ca-certificates (20161130+nmu1+deb9u1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Configurando openjdk-8-jre-headless:amd64 (8u181-b13-1~deb9u1) ...
Instalando nova versão do arquivo de configuração /etc/java-8-openjdk/security/java.security ...
Configurando openjdk-8-jdk-headless:amd64 (8u181-b13-1~deb9u1) ...
Configurando openjdk-8-jre:amd64 (8u181-b13-1~deb9u1) ...
Configurando openjdk-8-jdk:amd64 (8u181-b13-1~deb9u1) ...
Configurando libdevmapper1.02.1:amd64 (2:1.02.137-2) ...
Configurando dmsetup (2:1.02.137-2) ...
update-initramfs: deferring update (trigger activated)
Configurando eject (2.1.5+deb1+cvs20081104-13.2) ...
Configurando libcryptsetup4:amd64 (2:1.7.3-4) ...
A processar 'triggers' para systemd (232-25+deb9u4) ...
A processar 'triggers' para menu (2.1.47+b1) ...
A processar 'triggers' para libc-bin (2.24-11+deb9u3) ...
A processar 'triggers' para initramfs-tools (0.130) ...
update-initramfs: Generating /boot/initrd.img-4.9.0-1-amd64
A processar 'triggers' para rygel (0.32.1-3) ...
root@developer:/home/developer# apt-get install sqlite3
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  python3-cffi-backend python3-crypto python3-keyrings.alt python3-pyasn1
Utilize 'sudo apt autoremove' para os remover.
Pacotes sugeridos:
  sqlite3-doc
Os NOVOS pacotes a seguir serão instalados:
  sqlite3
0 pacotes atualizados, 1 pacotes novos instalados, 0 a serem removidos e 7 não atualizados.
É preciso baixar 784 kB de arquivos.
Depois desta operação, 2.355 kB adicionais de espaço em disco serão usados.
Obter:1 http://ftp.br.debian.org/debian stretch/main amd64 sqlite3 amd64 3.16.2-5+deb9u1 [784 kB]
Baixados 784 kB em 1s (581 kB/s) 
A seleccionar pacote anteriormente não seleccionado sqlite3.
(Lendo banco de dados ... 184840 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../sqlite3_3.16.2-5+deb9u1_amd64.deb ...
A descompactar sqlite3 (3.16.2-5+deb9u1) ...
Configurando sqlite3 (3.16.2-5+deb9u1) ...
A processar 'triggers' para man-db (2.7.6.1-2) ...
root@developer:/home/developer# apt-get install libsqlite3-dev
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  python3-cffi-backend python3-crypto python3-keyrings.alt python3-pyasn1
Utilize 'sudo apt autoremove' para os remover.
Pacotes sugeridos:
  sqlite3-doc
Os NOVOS pacotes a seguir serão instalados:
  libsqlite3-dev
0 pacotes atualizados, 1 pacotes novos instalados, 0 a serem removidos e 7 não atualizados.
É preciso baixar 704 kB de arquivos.
Depois desta operação, 2.063 kB adicionais de espaço em disco serão usados.
Obter:1 http://ftp.br.debian.org/debian stretch/main amd64 libsqlite3-dev amd64 3.16.2-5+deb9u1 [704 kB]
Baixados 704 kB em 1s (567 kB/s)        
A seleccionar pacote anteriormente não seleccionado libsqlite3-dev:amd64.
(Lendo banco de dados ... 184848 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../libsqlite3-dev_3.16.2-5+deb9u1_amd64.deb ...
A descompactar libsqlite3-dev:amd64 (3.16.2-5+deb9u1) ...
Configurando libsqlite3-dev:amd64 (3.16.2-5+deb9u1) ...
root@developer:/home/developer# apt-get install sqlitebrowser
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  python3-cffi-backend python3-crypto python3-keyrings.alt python3-pyasn1
Utilize 'sudo apt autoremove' para os remover.
The following additional packages will be installed:
  libqcustomplot1.3 libqt5printsupport5 libqt5scintilla2-12v5
  libqt5scintilla2-l10n libqt5test5
Os NOVOS pacotes a seguir serão instalados:
  libqcustomplot1.3 libqt5printsupport5 libqt5scintilla2-12v5
  libqt5scintilla2-l10n libqt5test5 sqlitebrowser
0 pacotes atualizados, 6 pacotes novos instalados, 0 a serem removidos e 7 não atualizados.
É preciso baixar 2.190 kB de arquivos.
Depois desta operação, 8.878 kB adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] s
Obter:1 http://ftp.br.debian.org/debian stretch/main amd64 libqt5printsupport5 amd64 5.7.1+dfsg-3+b1 [198 kB]
Obter:2 http://ftp.br.debian.org/debian stretch/main amd64 libqcustomplot1.3 amd64 1.3.2+dfsg1-1 [259 kB]
Obter:3 http://ftp.br.debian.org/debian stretch/main amd64 libqt5scintilla2-l10n all 2.9.3+dfsg-4 [49,5 kB]
Obter:4 http://ftp.br.debian.org/debian stretch/main amd64 libqt5scintilla2-12v5 amd64 2.9.3+dfsg-4 [824 kB]
Obter:5 http://ftp.br.debian.org/debian stretch/main amd64 libqt5test5 amd64 5.7.1+dfsg-3+b1 [120 kB]
Obter:6 http://ftp.br.debian.org/debian stretch/main amd64 sqlitebrowser amd64 3.9.1-2 [739 kB]
Baixados 2.190 kB em 1s (1.130 kB/s)   
A seleccionar pacote anteriormente não seleccionado libqt5printsupport5:amd64.
(Lendo banco de dados ... 184859 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../0-libqt5printsupport5_5.7.1+dfsg-3+b1_amd64.deb ...
A descompactar libqt5printsupport5:amd64 (5.7.1+dfsg-3+b1) ...
A seleccionar pacote anteriormente não seleccionado libqcustomplot1.3:amd64.
A preparar para desempacotar .../1-libqcustomplot1.3_1.3.2+dfsg1-1_amd64.deb ...
A descompactar libqcustomplot1.3:amd64 (1.3.2+dfsg1-1) ...
A seleccionar pacote anteriormente não seleccionado libqt5scintilla2-l10n.
A preparar para desempacotar .../2-libqt5scintilla2-l10n_2.9.3+dfsg-4_all.deb ...
A descompactar libqt5scintilla2-l10n (2.9.3+dfsg-4) ...
A seleccionar pacote anteriormente não seleccionado libqt5scintilla2-12v5.
A preparar para desempacotar .../3-libqt5scintilla2-12v5_2.9.3+dfsg-4_amd64.deb ...
A descompactar libqt5scintilla2-12v5 (2.9.3+dfsg-4) ...
A seleccionar pacote anteriormente não seleccionado libqt5test5:amd64.
A preparar para desempacotar .../4-libqt5test5_5.7.1+dfsg-3+b1_amd64.deb ...
A descompactar libqt5test5:amd64 (5.7.1+dfsg-3+b1) ...
A seleccionar pacote anteriormente não seleccionado sqlitebrowser.
A preparar para desempacotar .../5-sqlitebrowser_3.9.1-2_amd64.deb ...
A descompactar sqlitebrowser (3.9.1-2) ...
A processar 'triggers' para mime-support (3.60) ...
A processar 'triggers' para desktop-file-utils (0.23-1) ...
Configurando libqt5test5:amd64 (5.7.1+dfsg-3+b1) ...
Configurando libqt5scintilla2-l10n (2.9.3+dfsg-4) ...
Configurando libqt5printsupport5:amd64 (5.7.1+dfsg-3+b1) ...
A processar 'triggers' para libc-bin (2.24-11+deb9u3) ...
A processar 'triggers' para man-db (2.7.6.1-2) ...
A processar 'triggers' para hicolor-icon-theme (0.15-1) ...
Configurando libqcustomplot1.3:amd64 (1.3.2+dfsg1-1) ...
Configurando libqt5scintilla2-12v5 (2.9.3+dfsg-4) ...
Configurando sqlitebrowser (3.9.1-2) ...
A processar 'triggers' para libc-bin (2.24-11+deb9u3) ...
root@developer:/home/developer# cal
   Setembro 2018      
do se te qu qu se sá  
                   1  
 2  3  4  5  6  7  8  
 9 10 11 12 13 14 15  
16 17 18 19 20 21 22  
23 24 25 26 27 28 29  
30                    
root@developer:/home/developer# ac
bash: ac: comando não encontrado
root@developer:/home/developer# ipython
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
Type "copyright", "credits" or "license" for more information.

IPython 5.2.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from math import sqrt

In [2]: def raiz(num):
   ...:     return sqrt(num)
   ...: assert raiz(64) == 8
   ...: assert raiz(64) ==7
   ...: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-458741f4f396> in <module>()
      2     return sqrt(num)
      3 assert raiz(64) == 8
----> 4 assert raiz(64) ==7

AssertionError: 

In [3]: def raiz(num):
   ...:     return sqrt(num)
   ...: assert raiz(64) == 8
   ...: 

In [4]: def raiz(num):
   ...:     return sqrt(num)
   ...: assert raiz(64) == 7
   ...: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-0de81c066312> in <module>()
      1 def raiz(num):
      2     return sqrt(num)
----> 3 assert raiz(64) == 7

AssertionError: 

In [5]: def raiz(num):
   ...:     return sqrt(num)
   ...: assert raiz('36') == 6
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9ad76284f716> in <module>()
      1 def raiz(num):
      2     return sqrt(num)
----> 3 assert raiz('36') == 6

<ipython-input-5-9ad76284f716> in raiz(num)
      1 def raiz(num):
----> 2     return sqrt(num)
      3 assert raiz('36') == 6

TypeError: a float is required

In [6]: exit()
root@developer:/home/developer#